# This file was generated by stechec2-generator. DO NOT EDIT.

from enum import IntEnum
from typing import NamedTuple, List, Tuple  # noqa: F401

from _api import *


# Les 7 geisha (2, 2, 2, 3, 3, 4, 5)
NB_GEISHA = 7

# Le nombre total de cartes (2 + 2 + 2 + 3 + 3 + 4 + 5)
NB_CARTES_TOTALES = 21

# Le nombre de cartes que chaque personne a au début
NB_CARTES_DEBUT = 6

# Le nombre de cartes écartées au début du jeu
NB_CARTES_ECARTEES = 1

# Le nombre total d'action que chaque joueur devra faire
NB_ACTIONS = 4

# Le nombre total de manches avant la fin de la partie
NB_MANCHES_MAX = 3

# La valeur (et le nombre de cartes) de chaque geisha séparée par des |
GEISHA_VALEUR = "2|2|2|3|3|4|5"


class action(IntEnum):
    """
    Les actions de jeu
    """

    VALIDER = 0
    """Valide une unique carte"""

    DEFAUSSER = 1
    """Defausse deux cartes"""

    CHOIX_TROIS = 2
    """Donne le choix entre trois cartes"""

    CHOIX_PAQUETS = 3
    """Donne le choix entre deux paquets de deux cartes"""

    PREMIER_JOUEUR = 4
    """Aucune action n'a été jouée (utilisé dans tour_precedent)"""


class error(IntEnum):
    """
    Enumeration contentant toutes les erreurs possibles
    """

    OK = 0
    """pas d'erreur"""

    ACTION_DEJA_JOUEE = 1
    """l'action a déjà été jouée"""

    CARTES_INVALIDES = 2
    """vous ne pouvez pas jouer ces cartes"""

    PAQUET_INVALIDE = 3
    """ce paquet n'existe pas"""

    GEISHA_INVALIDES = 4
    """cette geisha n'existe pas (doit être un entier entre 0 et NB_GEISHA)"""

    JOUEUR_INVALIDE = 5
    """ce joueur n'existe pas"""

    CHOIX_INVALIDE = 6
    """vous ne pouvez pas repondre à ce choix"""

    ACTION_INVALIDE = 7
    """vous ne pouvez pas jouer cette action maintenant"""


class joueur(IntEnum):
    """
    Enumeration représentant les différents joueurs
    """

    JOUEUR_1 = 0
    """Le joueur 1"""

    JOUEUR_2 = 1
    """Le joueur 2"""

    EGALITE = 2
    """Égalité, utilisé uniquement dans possession_geisha"""


class action_jouee(NamedTuple):
    """
    La description d'une action jouée
    """

    act: action
    """L'action jouée"""

    c1: int
    """Si act==VALIDER ou act==DEFAUSSER, -1 sinon la première carte (du premier paquet)"""

    c2: int
    """Si act==V|D: -1 sinon la deuxième carte (du premier paquet)"""

    c3: int
    """Si act==V|D: -1 sinon la troisième carte (ou la première carte du second paquet si act==choix paquet)"""

    c4: int
    """Si act!=choix paquet: -1 sinon la deuxième carte du second paquet"""


